export const ACTIONS = {
    //TALKSWIPER ACTIONS

    TALK_RATE_LATER:'TALK_RATE_LATER',

    //TALKDETAIL  ACTIONS

    TALK_RATE:'TALK_RATE',
    GET_SPEAKERS_DETAILS:'GET_SPEAKERS_DETAILS',
    SELECT_SPEAKER:'SELECT_SPEAKER',
    TOGGLE_SPEAKER_DETAIL:'TOGGLE_SPEAKER_DETAIL',
    SET_CONTENT_PLACEHOLDER_STATE:'SET_CONTENT_PLACEHOLDER_STATE',

    // HOME ACTIONS
    SET_REVIEWED_LATER_CURRENT:'SET_REVIEWED_LATER_CURRENT',
    SET_REVIEWED_CURRENT:'SET_REVIEWED_CURRENT',
    SET_NOT_REVIEWED_CURRENT:'SET_NOT_REVIEWED_CURRENT',

    //FEED ACTIONS :
    INIT_TALKS:'INIT_TALKS',
    INIT_SPEAKERS : 'INIT_SPEAKERS'
};
