export const ACTIONS = {
    //LOGIN ACTIONS
    QR_CODE_READ: 'QR_CODE_READ',

    //TALKSWIPER ACTIONS

    TALK_RATE_LATER:'TALK_RATE_LATER',

    //TALKDETAIL  ACTIONS

    TALK_RATE:'TALK_RATE',
    GET_SPEAKERS_DETAILS:'GET_SPEAKERS_DETAILS',
    SELECT_SPEAKER:'SELECT_SPEAKER',
    TOGGLE_SPEAKER_DETAIL:'TOGGLE_SPEAKER_DETAIL',
    SET_CONTENT_PLACEHOLDER_STATE:'SET_CONTENT_PLACEHOLDER_STATE'
};
